export const DEFAULT_DATASOURCE_COLOR = [
    '#D8876C', '#AC8932', '#99A462',
    '#68A374', '#4F9FA1', '#5989C5',
    '#566CE8', '#9159D9', '#B1569B'
];

export type RedisCommand =
    | 'APPEND' | 'AUTH' | 'BGREWRITEAOF' | 'BGSAVE' | 'BITCOUNT' | 'BITFIELD' | 'BITOP' | 'BITPOS' | 'BLPOP' | 'BRPOP'
    | 'BRPOPLPUSH' | 'BZPOPMIN' | 'BZPOPMAX' | 'CLIENT' | 'CLUSTER' | 'COMMAND' | 'CONFIG' | 'DBSIZE' | 'DEBUG'
    | 'DECR' | 'DECRBY' | 'DEL' | 'DISCARD' | 'DUMP' | 'ECHO' | 'EVAL' | 'EVALSHA' | 'EXEC' | 'EXISTS' | 'EXPIRE'
    | 'EXPIREAT' | 'FLUSHALL' | 'FLUSHDB' | 'GEOADD' | 'GEOHASH' | 'GEOPOS' | 'GEODIST' | 'GEORADIUS' | 'GEORADIUSBYMEMBER'
    | 'GET' | 'GETBIT' | 'GETRANGE' | 'GETSET' | 'HDEL' | 'HEXISTS' | 'HGET' | 'HGETALL' | 'HINCRBY' | 'HINCRBYFLOAT'
    | 'HKEYS' | 'HLEN' | 'HMGET' | 'HMSET' | 'HSET' | 'HSETNX' | 'HSTRLEN' | 'HVALS' | 'INCR' | 'INCRBY' | 'INCRBYFLOAT'
    | 'INFO' | 'KEYS' | 'LASTSAVE' | 'LINDEX' | 'LINSERT' | 'LLEN' | 'LPOP' | 'LPUSH' | 'LPUSHX' | 'LRANGE' | 'LREM'
    | 'LSET' | 'LTRIM' | 'MEMORY' | 'MGET' | 'MIGRATE' | 'MONITOR' | 'MOVE' | 'MSET' | 'MSETNX' | 'OBJECT' | 'PERSIST'
    | 'PEXPIRE' | 'PEXPIREAT' | 'PFADD' | 'PFCOUNT' | 'PFMERGE' | 'PING' | 'PSETEX' | 'PSUBSCRIBE' | 'PTTL' | 'PUBLISH'
    | 'PUBSUB' | 'PUNSUBSCRIBE' | 'QUIT' | 'RANDOMKEY' | 'READONLY' | 'READWRITE' | 'RENAME' | 'RENAMENX' | 'RESTORE'
    | 'ROLE' | 'RPOP' | 'RPOPLPUSH' | 'RPUSH' | 'RPUSHX' | 'SADD' | 'SAVE' | 'SCARD' | 'SCRIPT' | 'SDIFF' | 'SDIFFSTORE'
    | 'SELECT' | 'SET' | 'SETBIT' | 'SETEX' | 'SETNX' | 'SETRANGE' | 'SHUTDOWN' | 'SINTER' | 'SINTERSTORE' | 'SISMEMBER'
    | 'SLAVEOF' | 'SLOWLOG' | 'SMEMBERS' | 'SMOVE' | 'SORT' | 'SPOP' | 'SRANDMEMBER' | 'SREM' | 'STRLEN' | 'SUBSCRIBE'
    | 'SUNION' | 'SUNIONSTORE' | 'SWAPDB' | 'SYNC' | 'TIME' | 'TOUCH' | 'TTL' | 'TYPE' | 'UNSUBSCRIBE' | 'UNLINK' | 'UNWATCH'
    | 'WAIT' | 'WATCH' | 'XACK' | 'XADD' | 'XLEN' | 'XPENDING' | 'XRANGE' | 'XREAD' | 'XREADGROUP' | 'XREVRANGE' | 'XTRIM'
    | 'ZADD' | 'ZCARD' | 'ZCOUNT' | 'ZINCRBY' | 'ZINTERSTORE' | 'ZLEXCOUNT' | 'ZPOPMAX' | 'ZPOPMIN' | 'ZRANGE' | 'ZRANGEBYLEX'
    | 'ZRANGEBYSCORE' | 'ZRANK' | 'ZREM' | 'ZREMRANGEBYLEX' | 'ZREMRANGEBYRANK' | 'ZREMRANGEBYSCORE' | 'ZREVRANGE'
    | 'ZREVRANGEBYLEX' | 'ZREVRANGEBYSCORE' | 'ZREVRANK' | 'ZSCORE' | 'ZUNIONSTORE' | 'SCAN' | 'SSCAN' | 'HSCAN' | 'ZSCAN';

export type RedisDataType = 'string' | 'list' | 'set' | 'zset' | 'hash' | 'stream' | 'unknown';

// 创建 Redis 命令映射对象
export const REDIS_CMD_TYPE: Record<RedisCommand, RedisDataType> = {
    // string 类型命令
    APPEND: 'string',
    DECR: 'string',
    DECRBY: 'string',
    GET: 'string',
    GETBIT: 'string',
    GETRANGE: 'string',
    GETSET: 'string',
    INCR: 'string',
    INCRBY: 'string',
    INCRBYFLOAT: 'string',
    MGET: 'string',
    MSET: 'string',
    MSETNX: 'string',
    PSETEX: 'string',
    SET: 'string',
    SETBIT: 'string',
    SETEX: 'string',
    SETNX: 'string',
    SETRANGE: 'string',
    STRLEN: 'string',
    // list 类型命令
    BLPOP: 'list',
    BRPOP: 'list',
    BRPOPLPUSH: 'list',
    LINDEX: 'list',
    LINSERT: 'list',
    LLEN: 'list',
    LPOP: 'list',
    LPUSH: 'list',
    LPUSHX: 'list',
    LRANGE: 'list',
    LREM: 'list',
    LSET: 'list',
    LTRIM: 'list',
    RPOP: 'list',
    RPOPLPUSH: 'list',
    RPUSH: 'list',
    RPUSHX: 'list',
    // set 类型命令
    SADD: 'set',
    SCARD: 'set',
    SDIFF: 'set',
    SDIFFSTORE: 'set',
    SINTER: 'set',
    SINTERSTORE: 'set',
    SISMEMBER: 'set',
    SMEMBERS: 'set',
    SMOVE: 'set',
    SPOP: 'set',
    SRANDMEMBER: 'set',
    SREM: 'set',
    SUNION: 'set',
    SUNIONSTORE: 'set',
    SSCAN: 'set',
    // zset 类型命令
    ZADD: 'zset',
    ZCARD: 'zset',
    ZCOUNT: 'zset',
    ZINCRBY: 'zset',
    ZINTERSTORE: 'zset',
    ZLEXCOUNT: 'zset',
    ZPOPMAX: 'zset',
    ZPOPMIN: 'zset',
    ZRANGE: 'zset',
    ZRANGEBYLEX: 'zset',
    ZRANGEBYSCORE: 'zset',
    ZRANK: 'zset',
    ZREM: 'zset',
    ZREMRANGEBYLEX: 'zset',
    ZREMRANGEBYRANK: 'zset',
    ZREMRANGEBYSCORE: 'zset',
    ZREVRANGE: 'zset',
    ZREVRANGEBYLEX: 'zset',
    ZREVRANGEBYSCORE: 'zset',
    ZREVRANK: 'zset',
    ZSCORE: 'zset',
    ZUNIONSTORE: 'zset',
    ZSCAN: 'zset',
    // hash 类型命令
    HDEL: 'hash',
    HEXISTS: 'hash',
    HGET: 'hash',
    HGETALL: 'hash',
    HINCRBY: 'hash',
    HINCRBYFLOAT: 'hash',
    HKEYS: 'hash',
    HLEN: 'hash',
    HMGET: 'hash',
    HMSET: 'hash',
    HSET: 'hash',
    HSETNX: 'hash',
    HSTRLEN: 'hash',
    HVALS: 'hash',
    HSCAN: 'hash',
    // stream 类型命令
    XACK: 'stream',
    XADD: 'stream',
    XLEN: 'stream',
    XPENDING: 'stream',
    XRANGE: 'stream',
    XREAD: 'stream',
    XREADGROUP: 'stream',
    XREVRANGE: 'stream',
    XTRIM: 'stream',
    // 其他未知类型的命令
    AUTH: 'unknown',
    BGREWRITEAOF: 'unknown',
    BGSAVE: 'unknown',
    BITCOUNT: 'unknown',
    BITFIELD: 'unknown',
    BITOP: 'unknown',
    BITPOS: 'unknown',
    BZPOPMIN: 'unknown',
    BZPOPMAX: 'unknown',
    CLIENT: 'unknown',
    CLUSTER: 'unknown',
    COMMAND: 'unknown',
    CONFIG: 'unknown',
    DBSIZE: 'unknown',
    DEBUG: 'unknown',
    DEL: 'unknown',
    DISCARD: 'unknown',
    DUMP: 'unknown',
    ECHO: 'unknown',
    EVAL: 'unknown',
    EVALSHA: 'unknown',
    EXEC: 'unknown',
    EXISTS: 'unknown',
    EXPIRE: 'unknown',
    EXPIREAT: 'unknown',
    FLUSHALL: 'unknown',
    FLUSHDB: 'unknown',
    GEOADD: 'unknown',
    GEOHASH: 'unknown',
    GEOPOS: 'unknown',
    GEODIST: 'unknown',
    GEORADIUS: 'unknown',
    GEORADIUSBYMEMBER: 'unknown',
    INFO: 'unknown',
    KEYS: 'unknown',
    LASTSAVE: 'unknown',
    MEMORY: 'unknown',
    MIGRATE: 'unknown',
    MONITOR: 'unknown',
    MOVE: 'unknown',
    OBJECT: 'unknown',
    PERSIST: 'unknown',
    PEXPIRE: 'unknown',
    PEXPIREAT: 'unknown',
    PFADD: 'unknown',
    PFCOUNT: 'unknown',
    PFMERGE: 'unknown',
    PING: 'unknown',
    PSUBSCRIBE: 'unknown',
    PTTL: 'unknown',
    PUBLISH: 'unknown',
    PUBSUB: 'unknown',
    PUNSUBSCRIBE: 'unknown',
    QUIT: 'unknown',
    RANDOMKEY: 'unknown',
    READONLY: 'unknown',
    READWRITE: 'unknown',
    RENAME: 'unknown',
    RENAMENX: 'unknown',
    RESTORE: 'unknown',
    ROLE: 'unknown',
    SAVE: 'unknown',
    SCRIPT: 'unknown',
    SELECT: 'unknown',
    SHUTDOWN: 'unknown',
    SLAVEOF: 'unknown',
    SLOWLOG: 'unknown',
    SORT: 'unknown',
    SUBSCRIBE: 'unknown',
    SWAPDB: 'unknown',
    SYNC: 'unknown',
    TIME: 'unknown',
    TOUCH: 'unknown',
    TTL: 'unknown',
    TYPE: 'unknown',
    UNSUBSCRIBE: 'unknown',
    UNLINK: 'unknown',
    UNWATCH: 'unknown',
    WAIT: 'unknown',
    WATCH: 'unknown',
    SCAN: 'unknown'
};
